# Generated by Django 5.2.15 on 2026-07-04 15:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investigations", "0002_evidencereference_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Machine-readable unique slug (e.g. 'clearbit', 'shodan').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version string of the provider implementation.",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "provider_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("degraded", "Degraded"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Routing priority; lower value = higher priority.",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum seconds allowed for a single discover() call.",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Maximum automatic retry attempts before marking a job failed.",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of DiscoveryCapability values this provider supports. Example: ["person_lookup", "email_lookup"].',
                    ),
                ),
                (
                    "last_health_check_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of the most recent health probe.",
                        null=True,
                    ),
                ),
                (
                    "last_health_status",
                    models.BooleanField(
                        blank=True,
                        help_text="True if the provider was healthy at last_health_check_at.",
                        null=True,
                    ),
                ),
                (
                    "last_health_message",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable message from the last health probe.",
                        max_length=500,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific credentials and endpoint settings. Encryption is the responsibility of the deployment layer.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-enable/disable. False prevents selection without altering provider_status.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Provider",
                "verbose_name_plural": "Discovery Providers",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("webhook", "Webhook"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="Mechanism that initiated this discovery job.",
                        max_length=20,
                    ),
                ),
                (
                    "capabilities_requested",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="DiscoveryCapability values requested from the provider.",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Provider-specific query payload (e.g. {"email": "..."}).',
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when provider.discover() began.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when the job reached a terminal state.",
                        null=True,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Wall-clock milliseconds between started_at and completed_at.",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Description of the most recent failure; preserved across retries.",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of retry attempts made after the initial failure.",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Intended execution time for deferred/scheduled jobs.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary diagnostics and tracing correlation metadata.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parent investigation (nullable for standalone enrichment jobs).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_jobs",
                        to="investigations.investigation",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="Investigation target being queried; preserved on target deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_jobs",
                        to="investigations.investigationtarget",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Provider assigned to execute this job.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_jobs",
                        to="osint.discoveryprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Job",
                "verbose_name_plural": "Discovery Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("relationship", "Relationship"),
                            ("asset", "Asset"),
                            ("indicator", "Indicator"),
                            ("document", "Document"),
                            ("raw", "Raw"),
                        ],
                        db_index=True,
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Normalised confidence in [0.0000, 1.0000]; DecimalField to avoid float drift.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Verbatim provider response fragment (preserved for audit).",
                    ),
                ),
                (
                    "normalised_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canonical representation after provider.normalize() has been applied.",
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Storage-agnostic key referencing a StoredFile in the configured StorageBackend (e.g. S3 object key).  Empty when no file artefact exists.",
                        max_length=1024,
                    ),
                ),
                (
                    "evidence_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the linked evidence.Evidence record.  Plain UUID (not FK) so the OSINT domain does not couple to the Evidence ORM model.  Populated by the identity resolution layer.",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="Canonical URL of the data source.", max_length=2000
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form label list for faceted search and filtering.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True when an analyst has confirmed the finding is accurate.",
                    ),
                ),
                (
                    "verified_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the verifying user (no FK to avoid user-model coupling).",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The discovery job that produced this result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="osint.discoveryjob",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provider that produced this result (denormalised from job.provider).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="osint.discoveryprovider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Result",
                "verbose_name_plural": "Discovery Results",
                "ordering": ["-confidence", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="discoveryprovider",
            index=models.Index(fields=["name"], name="osint_disco_name_fc82e0_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryprovider",
            index=models.Index(
                fields=["priority", "is_active"], name="osint_disco_priorit_49ea64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryprovider",
            index=models.Index(fields=["provider_status"], name="osint_disco_provide_63a9e3_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["status", "provider"], name="osint_disco_status_8ee24e_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(
                fields=["investigation", "status"], name="osint_disco_investi_ccf0f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["triggered_by"], name="osint_disco_trigger_89ce2e_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(fields=["job", "result_type"], name="osint_disco_job_id_bb7bcf_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(
                fields=["provider", "result_type"], name="osint_disco_provide_c93c86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(fields=["confidence"], name="osint_disco_confide_c34c10_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(fields=["is_verified"], name="osint_disco_is_veri_6f67f4_idx"),
        ),
    ]
