# Generated by Django 5.2.15 on 2026-07-05 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("metric_name", models.CharField(max_length=255)),
                ("threshold", models.FloatField()),
                ("condition", models.CharField(max_length=10)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cooldown_minutes", models.IntegerField(default=5)),
                ("notification_targets", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "observability_alertrule",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("component_health", models.JSONField(blank=True, default=dict)),
                ("active_connections", models.IntegerField(default=0)),
                ("queue_statistics", models.JSONField(blank=True, default=dict)),
                ("provider_status", models.JSONField(blank=True, default=dict)),
                ("recent_failures", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "observability_diagnostic_snapshot",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("component", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DEGRADED", "Degraded"),
                            ("UNHEALTHY", "Unhealthy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("last_check", models.DateTimeField(auto_now=True)),
                ("failure_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "observability_healthcheck",
                "ordering": ["-last_check"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "observability_metric",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Trace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("trace_id", models.CharField(db_index=True, max_length=255)),
                ("span_id", models.CharField(db_index=True, max_length=255)),
                (
                    "parent_span_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "causation_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "observability_trace",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_time", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="observability.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "observability_alert",
                "ordering": ["-trigger_time"],
            },
        ),
    ]
