# Generated by Django 5.2.15 on 2026-07-04 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("investigation", "Investigation"),
                            ("evidence", "Evidence"),
                            ("osint", "OSINT Discovery"),
                            ("organization", "Organization"),
                            ("workspace", "Workspace"),
                            ("custom", "Custom Node"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default="1.000", max_digits=4),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_nodes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_nodes",
                        to="organizations.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("member_of", "Member Of"),
                            ("resolves_to", "Resolves To"),
                            ("correlates_with", "Correlates With"),
                            ("discovered_by", "Discovered By"),
                            ("references", "References"),
                            ("contains", "Contains"),
                            ("custom", "Custom Relationship"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("direction", models.CharField(default="directed", max_length=20)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default="1.000", max_digits=4),
                ),
                ("provenance", models.CharField(default="system", max_length=255)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                ("investigation_references", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField()),
                ("label", models.CharField(max_length=255)),
                ("graph_data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_snapshots",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_snapshots",
                        to="organizations.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(
                fields=["tenant_id", "node_type"], name="graph_graph_tenant__ceb0b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(
                fields=["tenant_id", "workspace_id"], name="graph_graph_tenant__897d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["tenant_id", "source_node_id"], name="graph_graph_tenant__4ec041_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["tenant_id", "target_node_id"], name="graph_graph_tenant__a8020d_idx"
            ),
        ),
    ]
