# Generated by Django 5.2.15 on 2026-07-05 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("workflow_execution_id", models.UUIDField()),
                ("tenant_id", models.UUIDField()),
                (
                    "actor",
                    models.CharField(blank=True, help_text="User ID or 'system'", max_length=255),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "orchestration_execution_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "step_id",
                    models.CharField(
                        help_text="Identifier of the step in the Playbook DAG.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "logs",
                    models.JSONField(default=list, help_text="Execution logs and trace info."),
                ),
                ("outputs", models.JSONField(default=dict, help_text="Step output variables.")),
                ("errors", models.JSONField(default=list, help_text="List of errors if failed.")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orchestration_step_execution",
                "ordering": ["started_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_playbook",
                "ordering": ["-created_at"],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="PlaybookVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("definition", models.JSONField(help_text="The workflow DAG definition.")),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="orchestration.playbook",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_playbook_version",
                "ordering": ["-created_at"],
                "unique_together": {("playbook", "version")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "request_details",
                    models.JSONField(default=dict, help_text="Context presented to the analyst."),
                ),
                ("comments", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_request",
                        to="orchestration.stepexecution",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_approval_request",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("waiting_approval", "Waiting Approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                (
                    "execution_context",
                    models.JSONField(default=dict, help_text="Runtime variables and context."),
                ),
                (
                    "outputs",
                    models.JSONField(default=dict, help_text="Final outputs of the workflow."),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playbook_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="orchestration.playbookversion",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="workflow_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_executions",
                to="orchestration.workflowexecution",
            ),
        ),
    ]
