# Generated by Django 5.2.15 on 2026-07-05 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=100)),
                ("credentials_reference", models.CharField(blank=True, max_length=255)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("payload_hash", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                (
                    "integration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("rest", "REST"),
                            ("queue", "Queue"),
                            ("event_receiver", "Event Receiver"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("details", models.JSONField(default=dict)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=20
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("dropped", "Dropped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integrations.integrationendpoint",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255, null=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("provider_response_code", models.CharField(blank=True, max_length=50, null=True)),
                ("provider_response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_successful", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="integrations.integrationevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("event_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
