# Generated by Django 5.2.15 on 2026-07-04 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("domain", "Domain"),
                            ("email", "Email Address"),
                            ("phone", "Phone Number"),
                            ("username", "Username"),
                            ("ip_address", "IP Address"),
                            ("crypto_wallet", "Cryptocurrency Wallet"),
                            ("device", "Device"),
                            ("vehicle", "Vehicle"),
                            ("custom", "Custom Entity"),
                        ],
                        default="person",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=3, default="1.000", max_digits=4),
                ),
                (
                    "confidence_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Explainable score breakdown"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("osint", "OSINT Discovery"),
                            ("manual", "Manual Entry"),
                            ("import", "Data Import"),
                            ("api", "API Integration"),
                            ("merge", "Merged Provenance"),
                            ("ai", "AI-assisted Extraction"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="organizations.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Identities",
            },
        ),
        migrations.CreateModel(
            name="IdentityAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("domain", "Domain"),
                            ("email", "Email Address"),
                            ("phone", "Phone Number"),
                            ("username", "Username"),
                            ("ip_address", "IP Address"),
                            ("crypto_wallet", "Cryptocurrency Wallet"),
                            ("device", "Device"),
                            ("vehicle", "Vehicle"),
                            ("custom", "Custom Entity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("normalized_value", models.TextField(db_index=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default="1.000", max_digits=4),
                ),
                (
                    "evidence_references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of UUID reference strings to Evidence items",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="identity.identity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default="0.000", max_digits=4),
                ),
                (
                    "matching_strategy",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("normalized", "Normalized String Match"),
                            ("fuzzy", "Fuzzy String Similarity"),
                            ("email_normalization", "Email Normalization"),
                            ("phone_normalization", "Phone Normalization"),
                            ("username_normalization", "Username Normalization"),
                            ("domain_normalization", "Domain Normalization"),
                            ("composite", "Composite Attribute Matching"),
                        ],
                        default="composite",
                        max_length=50,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requires_review", "Requires Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "candidate_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_a",
                        to="identity.identity",
                    ),
                ),
                (
                    "candidate_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_b",
                        to="identity.identity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Match",
                "verbose_name_plural": "Identity Matches",
            },
        ),
        migrations.CreateModel(
            name="IdentityMergeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "source_identity_id",
                    models.UUIDField(
                        help_text="UUID of the original identity before being merged/deleted."
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("merge", "Merge"), ("split", "Split"), ("rollback", "Rollback")],
                        default="merge",
                        max_length=30,
                    ),
                ),
                (
                    "merge_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of identity attributes and relationships for rollback.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_histories",
                        to="identity.identity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Merge History",
                "verbose_name_plural": "Identity Merge Histories",
            },
        ),
        migrations.CreateModel(
            name="IdentityRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("owns", "Owns"),
                            ("manages", "Manages"),
                            ("employed_by", "Employed By"),
                            ("registered_to", "Registered To"),
                            ("communicates_with", "Communicates With"),
                            ("associated_with", "Associated With"),
                            ("controls", "Controls"),
                            ("uses", "Uses"),
                            ("member_of", "Member Of"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default="1.000", max_digits=4),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                (
                    "evidence_references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of UUID reference strings to Evidence items",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="identity.identity",
                    ),
                ),
                (
                    "target_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="identity.identity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["tenant_id", "entity_type"], name="identity_id_tenant__86e1a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["tenant_id", "workspace_id"], name="identity_id_tenant__413e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityattribute",
            index=models.Index(
                fields=["tenant_id", "type", "normalized_value"],
                name="identity_id_tenant__3e0c98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identitymatch",
            index=models.Index(
                fields=["tenant_id", "review_status"], name="identity_id_tenant__45e7d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitymatch",
            index=models.Index(
                fields=["tenant_id", "candidate_a", "candidate_b"],
                name="identity_id_tenant__f6f8d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identitymergehistory",
            index=models.Index(
                fields=["tenant_id", "source_identity_id"], name="identity_id_tenant__a24e5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitymergehistory",
            index=models.Index(
                fields=["tenant_id", "target_identity"], name="identity_id_tenant__3e6653_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityrelationship",
            index=models.Index(
                fields=["tenant_id", "source_identity", "target_identity"],
                name="identity_id_tenant__f5b67b_idx",
            ),
        ),
    ]
